/**
 * Country name to ISO 3166-1 alpha-2 code mapping
 * Used for flag display based on country names
 */

// Mapping of country names to ISO 3166-1 alpha-2 codes
export const countryNameToCode: Record<string, string> = {
  // Common variations and full names
  'united states': 'US',
  'the united states': 'US',
  'united states of america': 'US',
  'usa': 'US',
  'us': 'US',
  'mexico': 'MX',
  'chile': 'CL',
  'finland': 'FI',
  'canada': 'CA',
  'united kingdom': 'GB',
  'the united kingdom': 'GB',
  'uk': 'GB',
  'great britain': 'GB',
  'england': 'GB',
  'scotland': 'GB',
  'wales': 'GB',
  'germany': 'DE',
  'france': 'FR',
  'spain': 'ES',
  'italy': 'IT',
  'portugal': 'PT',
  'netherlands': 'NL',
  'holland': 'NL',
  'belgium': 'BE',
  'sweden': 'SE',
  'norway': 'NO',
  'denmark': 'DK',
  'poland': 'PL',
  'russia': 'RU',
  'brazil': 'BR',
  'argentina': 'AR',
  'australia': 'AU',
  'new zealand': 'NZ',
  'japan': 'JP',
  'china': 'CN',
  'south korea': 'KR',
  'korea': 'KR',
  'india': 'IN',
  'indonesia': 'ID',
  'thailand': 'TH',
  'vietnam': 'VN',
  'philippines': 'PH',
  'malaysia': 'MY',
  'singapore': 'SG',
  'taiwan': 'TW',
  'hong kong': 'HK',
  'israel': 'IL',
  'turkey': 'TR',
  'greece': 'GR',
  'austria': 'AT',
  'switzerland': 'CH',
  'czech republic': 'CZ',
  'czechia': 'CZ',
  'slovakia': 'SK',
  'hungary': 'HU',
  'romania': 'RO',
  'bulgaria': 'BG',
  'ukraine': 'UA',
  'ireland': 'IE',
  'iceland': 'IS',
  'estonia': 'EE',
  'latvia': 'LV',
  'lithuania': 'LT',
  'slovenia': 'SI',
  'croatia': 'HR',
  'serbia': 'RS',
  'south africa': 'ZA',
  'egypt': 'EG',
  'morocco': 'MA',
  'algeria': 'DZ',
  'tunisia': 'TN',
  'nigeria': 'NG',
  'kenya': 'KE',
  'saudi arabia': 'SA',
  'uae': 'AE',
  'united arab emirates': 'AE',
  'pakistan': 'PK',
  'bangladesh': 'BD',
  'iran': 'IR',
  'iraq': 'IQ',
  'afghanistan': 'AF',
  'colombia': 'CO',
  'peru': 'PE',
  'venezuela': 'VE',
  'ecuador': 'EC',
  'bolivia': 'BO',
  'paraguay': 'PY',
  'uruguay': 'UY',
  'costa rica': 'CR',
  'panama': 'PA',
  'cuba': 'CU',
  'jamaica': 'JM',
  'dominican republic': 'DO',
  'puerto rico': 'PR',
  'guatemala': 'GT',
  'honduras': 'HN',
  'el salvador': 'SV',
  'nicaragua': 'NI',
  'haiti': 'HT',
  'trinidad and tobago': 'TT',
  'sri lanka': 'LK',
  'myanmar': 'MM',
  'burma': 'MM',
  'cambodia': 'KH',
  'laos': 'LA',
  'nepal': 'NP',
  'bhutan': 'BT',
  'mongolia': 'MN',
  'north korea': 'KP',
  'maldives': 'MV',
  'cyprus': 'CY',
  'malta': 'MT',
  'luxembourg': 'LU',
  'monaco': 'MC',
  'andorra': 'AD',
  'san marino': 'SM',
  'vatican': 'VA',
  'vatican city': 'VA',
  'liechtenstein': 'LI',
  'albania': 'AL',
  'bosnia and herzegovina': 'BA',
  'bosnia': 'BA',
  'montenegro': 'ME',
  'kosovo': 'XK',
  'north macedonia': 'MK',
  'macedonia': 'MK',
  'moldova': 'MD',
  'belarus': 'BY',
  'georgia': 'GE',
  'armenia': 'AM',
  'azerbaijan': 'AZ',
  'kazakhstan': 'KZ',
  'uzbekistan': 'UZ',
  'turkmenistan': 'TM',
  'tajikistan': 'TJ',
  'kyrgyzstan': 'KG',
  'oman': 'OM',
  'yemen': 'YE',
  'syria': 'SY',
  'jordan': 'JO',
  'lebanon': 'LB',
  'kuwait': 'KW',
  'bahrain': 'BH',
  'qatar': 'QA',
  'new caledonia': 'NC',
  'fiji': 'FJ',
  'papua new guinea': 'PG',
  'solomon islands': 'SB',
  'vanuatu': 'VU',
  'samoa': 'WS',
  'tonga': 'TO',
  'micronesia': 'FM',
  'palau': 'PW',
  'marshall islands': 'MH',
  'kiribati': 'KI',
  'nauru': 'NR',
  'tuvalu': 'TV',
  'barbados': 'BB',
  'bahamas': 'BS',
  'belize': 'BZ',
  'guyana': 'GY',
  'suriname': 'SR',
  'french guiana': 'GF',
  'martinique': 'MQ',
  'guadeloupe': 'GP',
  'réunion': 'RE',
  'mayotte': 'YT',
  'guam': 'GU',
  'american samoa': 'AS',
  'northern mariana islands': 'MP',
  'virgin islands': 'VI',
  'us virgin islands': 'VI',
  'british virgin islands': 'VG',
  'cayman islands': 'KY',
  'bermuda': 'BM',
  'gibraltar': 'GI',
  'isle of man': 'IM',
  'channel islands': 'GG',
  'guernsey': 'GG',
  'jersey': 'JE',
  'faroe islands': 'FO',
  'greenland': 'GL',
  'svalbard': 'SJ',
  'jan mayen': 'SJ',
  'aland islands': 'AX',
  'aland': 'AX',
};
